version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16 # Use Node.js version 16

jobs:
  # 1. Install Packages
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - .

  # 2. Run Tests
  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Tests
          command: npm run test

  # 3. Build and Deploy to Docker Hub
  deploy:
    docker:
      - image: circleci/python:3.8  # Add python for docker-compose
    steps:
      - setup_remote_docker
      - checkout

      # Build the Docker image
      # - run:
      #     name: Build Docker Image
      #     command: |
      #       docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME .

      # # Log in to Docker Hub
      # - run:
      #     name: Docker Hub Login
      #     command: |
      #       echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # # Push the Docker image to Docker Hub
      # - run:
      #     name: Push Docker Image
      #     command: docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
